### ISSUE TITLE
user-identity is not allowed to access dispatchable index (dispatchable/index)

### ISSUE THREAD

**Issue by ghost** [bjyoungblood/ZfcUserAcl#5]
My role-id in database are: guest, auth and admin

So i don't understand why a setter in a getter:

$role->setRoleId('user-identity');

https://github.com/bjyoungblood/ZfcUserAcl/blob/master/src/ZfcUserAcl/Service/ZfcUserAclService.php#L113
and
https://github.com/bjyoungblood/ZfcUserAcl/blob/master/src/ZfcUserAcl/Service/RoleProvider.php#L13

**Comment by bjyoungblood** [comment]
The user-identity role will inherit from the roles that are assigned to the current user. This way users can have multiple roles. For example, you might have both the auth and the admin role (or on a blog for example, you might have editor and author).

As long as the main roles are set up correctly and they are assigned to your user (the user_role_linker table).

Here is an example of how to set up resources and rules: https://github.com/bjyoungblood/MtdTimeTracker/blob/master/module/Application/Module.php#L21-56

**Comment by ghost** [comment]
Ok i set up loadAclRules() and loadAclResources() into Module.php.
It's working fine.
But it should be great to put these rules into configuration files.
And how to combine  loadAclRules() and loadAclResources() with ZfcAcl config file (into autoload directory) :
https://github.com/ZF-Commons/ZfcAcl/blob/master/config/ZfcAcl.global.config.php.dist#L62
