### ISSUE TITLE
Fatal error: Class 'ZfcBase\Module\ModuleAbstract' not found in vendor\zf-commons\ZfcUserAcl\Module.php on line 12

### ISSUE THREAD

**Issue by ghost** [bjyoungblood/ZfcUserAcl#8]
Fatal error: Class 'ZfcBase\Module\ModuleAbstract' not found in vendor\zf-commons\ZfcUserAcl\Module.php on line 12

**Comment by bjyoungblood** [comment]
I'm waiting on documentation to the recent changes to ZfcBase.

Until then, please use ZF-Commons/ZfcBase@e1d6e8cce596841e4350396880e0b455f1a33a09

**Comment by ghost** [comment]
ZfcBase\Module\ModuleAbstract => ZfcBase\Module\AbstractModule

https://github.com/ZF-Commons/ZfcBase/commit/db78bc1de52680f3855c0acf9dde90f5fc6d4f5c

**Comment by bjyoungblood** [comment]
Yeah, but there were a lot more poorly-documented changes to ZfcBase that require more extensive modifications not only to ZfcUserAcl, but also to ZfcAcl and possibly ZfcUser. @EvanDotPro said he was going to try to get some more documentation on the changes.

**Comment by gmuehl** [comment]
Anything new on this Issue? I am getting the Same error.

**Comment by ghost** [comment]
ZfcUserAcl and ZfcAcl are not up to date anymore.
@EvanDotPro would like to replace them by BjyAuthorize (@bjyoungblood)
but some people don't agree and want to rewrite Zend\Acl.

https://github.com/ZF-Commons/RFC/issues/1
